/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'eric.shamow' at '11/3/15 10:41 AM' with Gradle 2.8
 *
 * @author eric.shamow, @date 11/3/15 10:41 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
